### ISSUE TITLE
Don't support null safety

### ISSUE THREAD

**Issue by asadbekdev** [minafarideleia/complete_advanced_flutter#159]
![image](https://user-images.githubusercontent.com/67022917/146673465-1c3325a2-1b48-4578-ba8a-13974af4b190.png)

**Comment by wisdom209** [comment]
Run flutter upgrade

**Comment by rodgav** [comment]
replace data_connection_checker for internet_connection_checker

**Comment by justinas-android** [comment]
same problem can you show us fix ? import 'package:internet_connection_checker/internet_connection_checker.dart';
no such package

**Comment by minafarideleia** [comment]
You can use **internet_connection_checker** package:

https://pub.dev/packages/internet_connection_checker/install
